spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/contact
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 12
      initialization-fail-timeout: 2

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration






