

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:15432/notification
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 12
      initialization-fail-timeout: 2
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual

  kafkaprops:
    pg-replica: v1.orders_dispatch
    order-placed-topic: v1.public.orders_outbox
    replication-factor: 1
    partitions-count: 3
    nack-sleep-duration: 100ms



server:
  port: 8090





